# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$username\
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$java\
$lua\
$nodejs\
$python\
$rust\
$ruby\
$terraform\
$memory_usage\
$docker_context\
$container\
$jobs\
$line_break\
$character"""

right_format = """
$cmd_duration\
$time\
$aws\
$gcloud\
$azure"""


[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style) '


[directory]
truncation_length = 0
truncate_to_repo = false
use_logical_path = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "cyan"
read_only = " \uf83d"
read_only_style = "red"

[directory.substitutions]
"Documents" = " 󰈙/"
"Downloads" = " /"
'~/dev/Personal/' = " 󰲋/"
'~/dev/Work/c1/' = " 󰲋/"

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[fill]
symbol = " "
style = "dimmed white"

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style) '

[gcloud]
# symbol = '️🇬️ '
# format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
format = '[$symbol$project]($style) '
detect_env_vars = ['GOOGLE_CLOUD_PROJECT', 'GOOGLE_CLOUD_PROJECT_ID', 'GCP_PROJECT', 'GCP_PROJECT_ID']
style = "blue"

# [gcloud.project_aliases]
# project_id = alias

[python]
style = 'bold blue'
symbol = ' '
format = ' via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
pyenv_version_name = true
pyenv_prefix = ' '

[time]
disabled = false
format = '[$time]($style) '
style = "white"


[os]
disabled = true
style = "bold cyan"

[os.symbols]
Windows = "󰍲/"
Ubuntu = "󰕈/"
Macos = "󰀵/"
Linux = "󰌽/"
Debian = "󰣚/"
Redhat = "󱄛/"
